Repository zowe/zlux-app-manager, pull requests merged in 2019-03, with the labels that each got.

#92 changes to proxy path logic to allow api ml integration
  bootstrap/src/uri/mvd-uri.ts
Labels: review

#93 fixed window handles move window for north and west handles
  virtual-desktop/src/app/window-manager/mvd-window-manager/shared/sizeable.directive.ts
Labels: review

#87 Detect session timeout & renew
  bootstrap/package-lock.json
  virtual-desktop/package-lock.json
  virtual-desktop/package.json
  virtual-desktop/pluginDefinition.json
  virtual-desktop/src/app/authentication-manager/authentication-manager.module.ts
  virtual-desktop/src/app/authentication-manager/authentication-manager.service.ts
  virtual-desktop/src/app/authentication-manager/login/login.component.html
  virtual-desktop/src/app/authentication-manager/login/login.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/desktop/desktop.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-widget/launchbar-widget.component.css
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-widget/launchbar-widget.component.html
Labels: deliverable, review

#94 Check previous state for maximised before restoring
  virtual-desktop/src/app/window-manager/mvd-window-manager/shared/desktop-window-state.ts
Labels: review

#97 websocket uri change for api-layer
  bootstrap/src/uri/mvd-uri.ts
Labels: review

#95 Personalization Panel + Language Switcher
  bootstrap/package-lock.json
  sonar-project.properties
  system-apps/app-prop-viewer/webClient/package-lock.json
  system-apps/system-settings-preferences/.gitignore
  system-apps/system-settings-preferences/LICENSE
  system-apps/system-settings-preferences/pluginDefinition.json
  system-apps/system-settings-preferences/webClient/angular.json
  system-apps/system-settings-preferences/webClient/package-lock.json
  system-apps/system-settings-preferences/webClient/package.json
  system-apps/system-settings-preferences/webClient/src/app/app.component.css
  system-apps/system-settings-preferences/webClient/src/app/app.component.html
  system-apps/system-settings-preferences/webClient/src/app/app.component.ts
  system-apps/system-settings-preferences/webClient/src/app/app.module.ts
  system-apps/system-settings-preferences/webClient/src/app/language/language.component.css
  system-apps/system-settings-preferences/webClient/src/app/language/language.component.html
  system-apps/system-settings-preferences/webClient/src/app/language/language.component.ts
  system-apps/system-settings-preferences/webClient/src/assets/icon.png
  system-apps/system-settings-preferences/webClient/src/assets/language_icon.png
  system-apps/system-settings-preferences/webClient/src/index.html
  system-apps/system-settings-preferences/webClient/src/main.ts
  system-apps/system-settings-preferences/webClient/src/plugin.ts
  system-apps/system-settings-preferences/webClient/src/polyfills.ts
  system-apps/system-settings-preferences/webClient/src/styles.css
  system-apps/system-settings-preferences/webClient/src/tsconfig.app.json
  system-apps/system-settings-preferences/webClient/src/typings.d.ts
  system-apps/system-settings-preferences/webClient/tsconfig.json
  system-apps/system-settings-preferences/webClient/tsconfig.ngx-i18n.json
  system-apps/system-settings-preferences/webClient/tslint.json
  system-apps/system-settings-preferences/webClient/webpack.config.js
  virtual-desktop/nodeServer/package-lock.json
  virtual-desktop/package-lock.json
  virtual-desktop/src/app/authentication-manager/login/login.component.ts
  virtual-desktop/src/app/i18n/globalization.ts
  virtual-desktop/src/app/i18n/language-locale.service.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/desktop/desktop.component.html
  virtual-desktop/src/app/window-manager/mvd-window-manager/desktop/desktop.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-icon/launchbar-icon.component.html
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-icon/launchbar-icon.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-instance-view/launchbar-instance-view.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-menu/launchbar-menu.component.css
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-menu/launchbar-menu.component.html
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-menu/launchbar-menu.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-widget/launchbar-widget.component.css
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-widget/launchbar-widget.component.html
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-widget/launchbar-widget.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar/launchbar.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/personalization-panel/personalization-panel.component.css
  virtual-desktop/src/app/window-manager/mvd-window-manager/personalization-panel/personalization-panel.component.html
  virtual-desktop/src/app/window-manager/mvd-window-manager/personalization-panel/personalization-panel.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/shared/window-manager.service.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/window-manager.module.ts
  virtual-desktop/src/assets/i18n/messages.en.json
  virtual-desktop/src/assets/i18n/messages.fr.json
  virtual-desktop/src/assets/i18n/messages.ja.json
  virtual-desktop/src/assets/i18n/messages.ru.json
  virtual-desktop/src/assets/i18n/messages.zh.json
  virtual-desktop/src/assets/i18n/messages.zh.xlf
  virtual-desktop/src/assets/images/launchbar/settings.png
  virtual-desktop/tsconfig.json
  virtual-desktop/tsconfig.ngx-i18n.json
Labels: Internationalization, deliverable, review
