Repository zowe/zlux-app-manager, pull requests merged in 2024-08, with the labels that each got.

#609 V2.x/http proxy update
  system-apps/web-browser-app/nodeServer/package-lock.json
  system-apps/web-browser-app/nodeServer/package.json
Labels: size/XS

#611 Add v2 in maintenance message to login screen
  virtual-desktop/src/app/authentication-manager/login/login.component.html
Labels: size/XS

#608 Typo in README.md
  system-apps/web-browser-app/README.md
Labels: size/XS

#614 New Desktop ID
  bootstrap/src/assets/i18n/log/messages_en.json
  bootstrap/src/bootstrap/bootstrap-manager.ts
  bootstrap/src/bootstrap/dsm-resources.ts
  bootstrap/src/bootstrap/rocket-mvd-resources.ts
  bootstrap/src/uri/dsm-uri.ts
  virtual-desktop/pluginDefinition.json
  virtual-desktop/src/app/shared/logger.ts
  virtual-desktop/src/app/start-url-manager/start-url-manager.service.ts
Labels: size/L

#618 Update build workflow
  .github/workflows/build-core.yml
Labels: size/XS

#613 Load plugins by entrypoint urls if defined
  virtual-desktop/src/app/plugin-manager/plugin-factory/angular2/angular2-plugin-factory.ts
  virtual-desktop/src/app/plugin-manager/plugin-factory/react/react-plugin-factory.ts
Labels: size/S

#621 Fix not loading right desktop due to incorrect filter
  bootstrap/src/bootstrap/bootstrap-manager.ts
Labels: size/XS

#622 Fix iframe adapter
  virtual-desktop/src/app/plugin-manager/plugin-factory/iframe/iframe-plugin-factory.ts
Labels: size/XS
