Repository zowe/zlux-app-manager, pull requests merged in 2024-09, with the labels that each got.

#625 Combined build and externals script to aid pipeline
  virtual-desktop-v2/package-lock.json
  virtual-desktop-v2/package.json
  virtual-desktop/src/app/window-manager/mvd-window-manager/personalization-panel/personalization-panel.component.ts
Labels: size/S

#623 Small CSS fixes
  virtual-desktop/plugin-config/webpack5.base.js
  virtual-desktop/src/app/shared/include-external-css.component.ts
  virtual-desktop/src/app/window-manager/mvd-window-manager/desktop/desktop.component.html
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar-icon/launchbar-icon.component.css
  virtual-desktop/src/app/window-manager/mvd-window-manager/launchbar/launchbar/launchbar.component.html
  virtual-desktop/src/app/window-manager/simple-window-manager/simple.component.html
  virtual-desktop/src/assets/css/desktop.css
Labels: size/M

#629 Add app-prop-viewer entryPoint for v3, change build path for v3 to web/v3
  system-apps/app-prop-viewer/pluginDefinition.json
  system-apps/app-prop-viewer/webClient/package.json
  system-apps/app-prop-viewer/webClient/src/app/app.component.ts
  system-apps/app-prop-viewer/webClient/src/index.html
  system-apps/app-prop-viewer/webClient/webpack.config.js
Labels: size/S

#637 Fix typo in angular and react plugin factory
  virtual-desktop/src/app/plugin-manager/plugin-factory/angular2/angular2-plugin-factory.ts
  virtual-desktop/src/app/plugin-manager/plugin-factory/react/react-plugin-factory.ts
Labels: size/XS

#631 Remove uppercase visualization for Edge login input (v2)
  virtual-desktop/src/app/authentication-manager/login/login.component.css
Labels: size/XS

#630 Remove uppercase visualization for Edge login input
  virtual-desktop/src/app/authentication-manager/login/login.component.css
Labels: size/XS

#639 Updated changelog
  CHANGELOG.md
Labels: size/XS
